header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: TiKV Project Authors.
  paths-ignore:
    - 'config/'
    - 'dev/'
    - 'docs/'
    - 'metrics/'
    - 'scripts/'
    - 'LICENSE'
    - 'Makefile'
    - 'pom.xml'
    - 'spotbugs-include.xml'
    - 'shell.nix'
    - '.ci/'
    - '.gitignore'
    - '.gitattributes'
    - '.github/'
    - '**/*.md'
    - '**/*.properties'
    - '**/*.json'
    - '**/*.pem'
    - '**/*.crt'
    - '**/*.g4'
  comment: on-failure
