{
 "title": "Client-Java-Summary",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(client_java_raw_requests_latency_count, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Service Quality", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(client_java_raw_requests_latency_count{instance=~\"$instance\"}[$__interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Request Failure OPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(client_java_raw_requests_failure_total[$__interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Request Duration 99th",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(client_java_raw_requests_latency_bucket{instance=~\"$instance\"}[$__interval])) by (le, type))",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(client_java_raw_requests_latency_bucket{instance=~\"$instance\"}[$__interval])) by (le, type))"
    }
   ]
  },
  {
   "title": "Request Duration Avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(client_java_raw_requests_latency_sum{instance=~\"$instance\"}[$__interval])) by (type) / sum(rate(client_java_raw_requests_latency_count{instance=~\"$instance\"}[$__interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Causes of TiKV Request Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Request Duration + Backoff (Single Run) 99th",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(client_java_grpc_raw_requests_latency_bucket{instance=~\"$instance\"}[$__interval])) by (le, type))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Request Duration + Backoff (Single Run) Avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(client_java_grpc_raw_requests_latency_sum{instance=~\"$instance\"}[$__interval])) by (type) / sum(rate(client_java_grpc_raw_requests_latency_count{instance=~\"$instance\"}[$__interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "TiKV Request Duration (Single Run) 99th",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(client_java_grpc_single_requests_latency_bucket{instance=~\"$instance\", type!=\"pdpb.PD/GetRegion\", type!=\"pdpb.PD/GetStore\"}[$__interval])) by (le, type))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "TiKV Request Duration (Single Run) Avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(client_java_grpc_single_requests_latency_sum{instance=~\"$instance\", type!=\"pdpb.PD/GetRegion\", type!=\"pdpb.PD/GetStore\"}[$__interval])) by (type) / sum(rate(client_java_grpc_single_requests_latency_count{instance=~\"$instance\", type!=\"pdpb.PD/GetRegion\", type!=\"pdpb.PD/GetStore\"}[$__interval])) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Backoff: Seek Leader Store Duration (Single Run)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(client_java_seek_leader_store_duration_sum{instance=~\"$instance\"}[$__interval])) by (le) / sum(rate(client_java_seek_leader_store_duration_count{instance=~\"$instance\"}[$__interval])) by (le)",
     "legendFormat": "seek-leader-store-avg"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(client_java_seek_leader_store_duration_bucket{instance=~\"$instance\"}[$__interval])) by (le, type))",
     "legendFormat": "seek-leader-store-99"
    }
   ]
  },
  {
   "title": "Backoff: Seek Proxy Store Duration (Single Run)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(client_java_seek_proxy_store_duration_sum{instance=~\"$instance\"}[$__interval])) by (le) / sum(rate(client_java_seek_proxy_store_duration_count{instance=~\"$instance\"}[$__interval])) by (le)",
     "legendFormat": "seek-proxy-store-avg"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(client_java_seek_proxy_store_duration_bucket{instance=~\"$instance\"}[$__interval])) by (le, type))",
     "legendFormat": "seek-proxy-store-99"
    }
   ]
  },
  {
   "title": "Backoff Duration (Single Run + Inter-Run) Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(client_java_backoff_duration_sum{instance=~\"$instance\", type!=\"BoPDRPC\"}[$__interval])) by (le, type)",
     "legendFormat": "{{type}}-total"
    }
   ]
  },
  {
   "title": "Backoff OPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(client_java_backoff_duration_count{instance=~\"$instance\"}[$__interval])) by (le, type)",
     "legendFormat": "{{type}}-count"
    }
   ]
  },
  {
   "title": "Backoff Duration (Single Run + Inter-Run) Avg",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(client_java_backoff_duration_sum{instance=~\"$instance\", type!=\"BoPDRPC\"}[$__interval])) by (le, type) / sum(rate(client_java_backoff_duration_count{instance=~\"$instance\", type!=\"BoPDRPC\"}[$__interval])) by (le, type)",
     "legendFormat": "{{type}}-avg"
    }
   ]
  },
  { "title": "Causes of PD Request Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Get Region from Cache/PD Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(client_java_get_region_by_requests_latency_sum{instance=~\"$instance\"}[$__interval])) / sum(rate(client_java_get_region_by_requests_latency_count{instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(client_java_get_region_by_requests_latency_bucket{instance=~\"$instance\"}[$__interval])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "Region Cache Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - sum(rate(client_java_grpc_single_requests_latency_count{instance=~\"$instance\", type=\"pdpb.PD/GetRegion\"}[$__interval])) / sum(rate(client_java_get_region_by_requests_latency_count{instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "hit ratio"
    }
   ]
  },
  {
   "title": "PD Request Duration 99th",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(client_java_grpc_single_requests_latency_bucket{instance=~\"$instance\", type=\"pdpb.PD/GetStore\"}[$__interval])) by (le, type))",
     "legendFormat": "{{ type }}-99th"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(client_java_grpc_single_requests_latency_bucket{instance=~\"$instance\", type=\"pdpb.PD/GetRegion\"}[$__interval])) by (le, type))",
     "legendFormat": "{{ type }}-99th"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(client_java_grpc_single_requests_latency_bucket{instance=~\"$instance\", type=\"pdpb.PD/GetMembers\"}[$__interval])) by (le, type))",
     "legendFormat": "{{ type }}-99th"
    }
   ]
  },
  {
   "title": "PD Request OPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(client_java_grpc_single_requests_latency_count{instance=~\"$instance\", type=\"pdpb.PD/GetRegion\"}[$__interval])) by (type)",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(rate(client_java_grpc_single_requests_latency_count{instance=~\"$instance\", type=\"pdpb.PD/GetStore\"}[$__interval])) by (type)",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(rate(client_java_grpc_single_requests_latency_count{instance=~\"$instance\", type=\"pdpb.PD/GetMembers\"}[$__interval])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Backoff Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(client_java_backoff_duration_sum{instance=~\"$instance\", type=\"BoPDRPC\"}[$__interval])) by (le, type) / sum(rate(client_java_backoff_duration_count{instance=~\"$instance\", type=\"BoPDRPC\"}[$__interval])) by (le, type)",
     "legendFormat": "{{type}}-avg"
    },
    {
     "expr": "sum(rate(client_java_backoff_duration_sum{instance=~\"$instance\", type=\"BoPDRPC\"}[$__interval])) by (le, type)",
     "legendFormat": "{{type}}-sum"
    }
   ]
  },
  {
   "title": "Backoff OPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(client_java_backoff_duration_count{instance=~\"$instance\", type=\"BoPDRPC\"}[$__interval])) by (le, type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "PD seek leader/proxy duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(client_java_pd_seek_leader_duration_bucket{instance=\"$instance\"}[5s])))",
     "legendFormat": "seek-pd-leader-99"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(client_java_pd_seek_proxy_duration_bucket{instance=\"$instance\"}[5s])))",
     "legendFormat": "seek-pd-proxy-99"
    }
   ]
  }
 ]
}