name: 'Stale Checker'
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          days-before-stale: 30
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity.'
          stale-issue-label: 'status/stale'
          days-before-issue-close: -1
          stale-pr-message: 'This PR is stale because it has been open 30 days with no activity. Remove the status/stale label or comment or this PR will be closed in 7 days.'
          stale-pr-label: 'status/stale'
          days-before-pr-close: 7
          close-pr-message: 'This PR was closed because it has been stalled for 7 days with no activity.'
